services:
  jellyfin:
    image: jellyfin/jellyfin
    # user: root:root # user:group / acredito que nao precisa dessa configuracao pode fechar / Configurado para o play with docker
    # network_mode: 'host' # Se ativado ignora a ports e joga no porta 8096
    restart: 'unless-stopped'
    environment: # Configura as variaveis das pastas / o que vai aparecer no jellyfin
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin 
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
    volumes: # Mapaia para a pasta /root/jellyfin para poder fazer o s3fs
      - /home/ubuntu/efs-jellyfin/config:/etc/jellyfin
      - /home/ubuntu/efs-jellyfin/cache:/var/cache/jellyfin
      - /home/ubuntu/efs-jellyfin/data:/var/lib/jellyfin
      - /home/ubuntu/efs-jellyfin/log:/var/log/jellyfin
      - /home/ubuntu/s3-jellyfin/media:/var/media/jellyfin
    ports:
      - "80:8096" # Joga na porta 80
      - "443:8920" # Joga na porta 443